/* 
   Este arquivo faz parte da JCFLIGHT.   
   JCFLIGHT é um software livre: você pode redistribuí-lo e/ou modificar 
   sob os termos da GNU General Public License conforme publicada por 
   a Free Software Foundation, seja a versão 3 da Licença, ou 
   (à sua escolha) qualquer versão posterior. 
   
   JCFLIGHT é distribuído na esperança de ser útil, 
   mas SEM QUALQUER GARANTIA; sem mesmo a garantia implícita de 
   COMERCIALIZAÇÃO ou ADEQUAÇÃO A UM DETERMINADO FIM. Veja o 
   GNU General Public License para mais detalhes. 
   
   Você deve ter recebido uma cópia da Licença Pública Geral GNU 
   junto com a JCFLIGHT. Caso contrário, consulte <http://www.gnu.org/licenses/>. 
*/

#pragma once

/*
BAR - BASE ADDRESS REGISTER

ESSE ARQUIVO HEADER FOI GERADO AUTOMATICAMENTE - POR FAVOR,NÃO O EDITE MANUALMENTE!

ATUALIZADO EM 20/05/2021 ÁS 21:44:46
*/

//INCREMENTE SEMPRE QUE HOUVER UM NOVO LANÇAMENTO
#define FIRMWARE_STORAGE_REVISION 10 //1.0

//NÚMERO DE BYTES DO ARMAZENAMENTO RESERVADOS PARA USO
#define TOTAL_SIZE_OF_STORAGE 2000

//ENDEREÇO PARA VERIFICAR SE É O PRIMEIRO UPLOAD DA VERSÃO DO FIRMWARE
#define FIRMWARE_MAGIC_ADDRESS 1500

//ENDEREÇOS PARA O CLI
#define KP_ACC_AHRS_ADDR 2
#define KI_ACC_AHRS_ADDR 3
#define KP_MAG_AHRS_ADDR 4
#define KI_MAG_AHRS_ADDR 5
#define AL_AHRS_BA_ADDR 6
#define AL_IMU_BA_ADDR 8
#define AL_IMU_GPS_VEL_ADDR 9
#define AL_TRIGGER_MOTOR_DELAY_ADDR 10
#define AL_ELEVATOR_ADDR 12
#define AL_SPINUP_ADDR 13
#define AL_SPINUP_TIME_ADDR 15
#define AL_MAX_THROTTLE_ADDR 17
#define AL_EXIT_ADDR 19
#define AL_ALTITUDE_ADDR 21
#define BATT_VOLTAGE_FACTOR_ADDR 25
#define BATT_AMPS_VOLT_ADDR 29
#define BATT_AMPS_OFFSET_ADDR 33
#define CC_BANKANGLE_ADDR 37
#define CC_TIME_ADDR 38
#define GIMBAL_MIN_ADDR 39
#define GIMBAL_MAX_ADDR 41
#define LAND_CHECKACC_ADDR 43
#define THROTTLE_FACTOR_ADDR 44
#define AUTODISARM_ADDR 48
#define AUTODISARM_THR_MIN_ADDR 50
#define AUTODISARM_YPR_MIN_ADDR 52
#define AUTODISARM_YPR_MAX_ADDR 54
#define WHEELS_ADDR 56
#define GPS_BAUDRATE_ADDR 58
#define NAV_VEL_ADDR 59
#define WP_RADIUS_ADDR 61
#define RTH_LAND_ADDR 62
#define GPS_TILT_COMP_ADDR 63
#define AIRSPEED_SAMPLES_ADDR 64
#define AIRSPEED_FACTOR_ADDR 65
#define ARM_TIME_SAFETY_ADDR 69
#define DISARM_TIME_SAFETY_ADDR 70
#define COMPASS_CAL_TIME_ADDR 71
#define AUTO_PILOT_MODE_ADDR 72
#define AS_AUTO_CAL_SCALE_ADDR 73

//ENDEREÇOS PARA AS CONFIGS
#define ACC_ROLL_OFFSET_ADDR 481
#define ACC_PITCH_OFFSET_ADDR 483
#define ACC_YAW_OFFSET_ADDR 485

//CONFIGURAÇÕES E ENDEREÇOS PARA O MODO WAYPOINT
#define WAYPOINTS_MAXIMUM 10 //NÚMERO MAXIMO DE WAYPOINTS SUPORTADO
#define OTHERS_PARAMS_MAXIMUM 3 //ALTITUDE,TEMPO DO GPS-HOLD E O MODO DE VOO
#define INITIAL_ADDR_OF_COORDINATES 1000
#define FINAL_ADDR_OF_COORDINATES 1080
#define INITIAL_ADDR_OF_OTHERS_PARAMS 1084
#define FINAL_ADDR_OF_OTHERS_PARAMS 1495
