  Variavel: ReferenceAirSpeed
  Valor Min: 1
  Valor Max: 5000
  Nome: Referência de velocidade no ar
  Descrição: É usado para cálculo de curva coordenada se o tubo de pitot não estiver presente."
  Valor Padrão: "1000"

  Variavel: CoordinatedPitchGain
  Valor Min: 0
  Valor Max: 2
  Nome: Turn Pitch Ganho
  Descrição: "Ganho necessário para manter o ângulo de inclinação constante durante curvas coordenadas (modo Turn-Coord.).O valor diferente de 1.0 indica um problema com a calibração do tubo de pitot (se houver),ou o valor do parâmetro `Reference_AirSpeed`"
  Valor Padrão: "1.0"

  Variavel: CoordinatedPitchYaw
  Valor Min: 0
  Valor Max: 2
  Nome: Turn Yaw Ganho
  Descrição: "Ganho necessário para manter a taxa de guinada consistente com a taxa de curva para uma curva coordenada (modo Turn-Coord.).O valor diferente de 1.0 indica um problema com a calibração do tubo de pitot (se houver),ou o valor do parâmetro `Reference_AirSpeed`"
  Valor Padrão: "1.0"
