/*
   Este arquivo faz parte da JCFLIGHT.

   JCFLIGHT é um software livre: você pode redistribuí-lo e/ou modificar
   sob os termos da GNU General Public License conforme publicada por
   a Free Software Foundation, seja a versão 3 da Licença, ou
   (à sua escolha) qualquer versão posterior.

  JCFLIGHT é distribuído na esperança de ser útil,
  mas SEM QUALQUER GARANTIA; sem mesmo a garantia implícita de
  COMERCIALIZAÇÃO ou ADEQUAÇÃO A UM DETERMINADO FIM. Veja o
  GNU General Public License para mais detalhes.

   Você deve ter recebido uma cópia da Licença Pública Geral GNU
  junto com a JCFLIGHT. Caso contrário, consulte <http://www.gnu.org/licenses/>.
*/

#ifndef RCDEFINES_H_
#define RCDEFINES_H_
#include "BitArray/BITARRAY.h"
#include "RadioControl/DECODE.h"
#define RANGE_MIN 900
#define MIN_PULSE 1100
#define MAX_PULSE 1900
#define MIN_STICKS_PULSE 1000
#define MAX_STICKS_PULSE 2000
#define MIDDLE_STICKS_PULSE (MIN_STICKS_PULSE + MAX_STICKS_PULSE) / 2
#define DISABLE_IO_PIN 0
#define FLIGHT_MODE_PULSE_OFF_SET 200
#define USE_POS_HOLD_TYPE_TOTAL_AUTO_PILOT
//AUX1
#define AUX1_LOW DECODE.GetRxChannelOutput(AUX1) < MIN_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET
#define AUX1_MID DECODE.GetRxChannelOutput(AUX1) > (MIDDLE_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET) && DECODE.GetRxChannelOutput(AUX1) < (MIDDLE_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET)
#define AUX1_HIGH DECODE.GetRxChannelOutput(AUX1) > MAX_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET
//AUX2
#define AUX2_LOW DECODE.GetRxChannelOutput(AUX2) < MIN_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET
#define AUX2_MID DECODE.GetRxChannelOutput(AUX2) > (MIDDLE_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET) && DECODE.GetRxChannelOutput(AUX2) < (MIDDLE_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET)
#define AUX2_HIGH DECODE.GetRxChannelOutput(AUX2) > MAX_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET
//AUX3
#define AUX3_LOW DECODE.GetRxChannelOutput(AUX3) < MIN_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET
#define AUX3_MID DECODE.GetRxChannelOutput(AUX3) > (MIDDLE_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET) && DECODE.GetRxChannelOutput(AUX3) < (MIDDLE_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET)
#define AUX3_HIGH DECODE.GetRxChannelOutput(AUX3) > MAX_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET
//AUX4
#define AUX4_LOW DECODE.GetRxChannelOutput(AUX4) < MIN_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET
#define AUX4_MID DECODE.GetRxChannelOutput(AUX4) > (MIDDLE_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET) && DECODE.GetRxChannelOutput(AUX4) < (MIDDLE_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET)
#define AUX4_HIGH DECODE.GetRxChannelOutput(AUX4) > MAX_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET
//AUX5
#define AUX5_LOW DECODE.GetRxChannelOutput(AUX5) < MIN_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET
#define AUX5_MID DECODE.GetRxChannelOutput(AUX5) > (MIDDLE_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET) && DECODE.GetRxChannelOutput(AUX5) < (MIDDLE_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET)
#define AUX5_HIGH DECODE.GetRxChannelOutput(AUX5) > MAX_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET
//AUX6
#define AUX6_LOW DECODE.GetRxChannelOutput(AUX6) < MIN_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET
#define AUX6_MID DECODE.GetRxChannelOutput(AUX6) > (MIDDLE_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET) && DECODE.GetRxChannelOutput(AUX6) < (MIDDLE_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET)
#define AUX6_HIGH DECODE.GetRxChannelOutput(AUX6) > MAX_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET
//AUX7
#define AUX7_LOW DECODE.GetRxChannelOutput(AUX7) < MIN_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET
#define AUX7_MID DECODE.GetRxChannelOutput(AUX7) > (MIDDLE_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET) && DECODE.GetRxChannelOutput(AUX7) < (MIDDLE_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET)
#define AUX7_HIGH DECODE.GetRxChannelOutput(AUX7) > MAX_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET
//AUX8
#define AUX8_LOW DECODE.GetRxChannelOutput(AUX8) < MIN_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET
#define AUX8_MID DECODE.GetRxChannelOutput(AUX8) > (MIDDLE_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET) && DECODE.GetRxChannelOutput(AUX8) < (MIDDLE_STICKS_PULSE + FLIGHT_MODE_PULSE_OFF_SET)
#define AUX8_HIGH DECODE.GetRxChannelOutput(AUX8) > MAX_STICKS_PULSE - FLIGHT_MODE_PULSE_OFF_SET
#endif